/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UINam;

import BUS.Generic_BUS;
import static DAO.ChitiethoadonHome.getTheoSLGiayVaThang;
import entity1.Chitiethoadon;
import entity1.Hoadon;
import entity1.Sanpham;
import java.awt.Color;
import java.awt.GradientPaint;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;

import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author NAM
 */
public class ThongKeFormOld extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeForm
     */
    public ArrayList<Object[]> results;
    public ArrayList<Chitiethoadon> dscthd;
    public ArrayList<Sanpham> dssp;
    public ArrayList<Hoadon> listhd;

    public ThongKeFormOld() {
        results = getTheoSLGiayVaThang();
        dscthd = Generic_BUS.getAll(Chitiethoadon.class);
        dssp = Generic_BUS.getAll(Sanpham.class);
        listhd = Generic_BUS.getAll(Hoadon.class);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        tkdt = new javax.swing.JLabel();
        tktngay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tktthang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tkspbanchay = new javax.swing.JPanel();
        tkspBanChay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        containerPanel.setBackground(new java.awt.Color(0, 102, 102));
        containerPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        tkdt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tkdt.setForeground(new java.awt.Color(204, 255, 204));
        tkdt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tkdt.setText("THỐNG KÊ DOANH THU");

        tktngay.setBackground(new java.awt.Color(0, 102, 102));
        tktngay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true));
        tktngay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tktngay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tktngayMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thống kê theo ngày");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tktngayLayout = new javax.swing.GroupLayout(tktngay);
        tktngay.setLayout(tktngayLayout);
        tktngayLayout.setHorizontalGroup(
            tktngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tktngayLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135))
        );
        tktngayLayout.setVerticalGroup(
            tktngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        tktthang.setBackground(new java.awt.Color(0, 102, 102));
        tktthang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true));
        tktthang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tktthang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tktthangMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thống kê theo tháng");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tktthangLayout = new javax.swing.GroupLayout(tktthang);
        tktthang.setLayout(tktthangLayout);
        tktthangLayout.setHorizontalGroup(
            tktthangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tktthangLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(129, 129, 129))
        );
        tktthangLayout.setVerticalGroup(
            tktthangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        tkspbanchay.setBackground(new java.awt.Color(0, 102, 102));
        tkspbanchay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true));
        tkspbanchay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkspbanchay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tkspbanchayMouseClicked(evt);
            }
        });

        tkspBanChay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tkspBanChay.setForeground(new java.awt.Color(204, 255, 204));
        tkspBanChay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tkspBanChay.setText("Thống kê sản phẩm bán chạy nhất (theo tháng)");
        tkspBanChay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkspBanChay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tkspBanChayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tkspbanchayLayout = new javax.swing.GroupLayout(tkspbanchay);
        tkspbanchay.setLayout(tkspbanchayLayout);
        tkspbanchayLayout.setHorizontalGroup(
            tkspbanchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tkspbanchayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tkspBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        tkspbanchayLayout.setVerticalGroup(
            tkspbanchayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tkspBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tkspbanchay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tktthang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tktngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
            .addComponent(tkdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tkdt, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(tktngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tktthang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tkspbanchay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static class Cus {

        public Date ngay;
        public Double doanhthu;
        public int soluong;

        public Cus() {
        }
    }

    public static class CusMonth {

        public int thang;
        public Double doanhthu;
        public int soluong;

        public CusMonth() {

        }
    }


    private void tktngayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tktngayMouseClicked

        Set<Date> SetNgay = new HashSet<>(); // 
        Set<Integer> SetThang = new HashSet<>();

        for (Hoadon e : listhd) {
            SetNgay.add(e.getNgayLap());
        }

        for (Hoadon e : listhd) {
            SetThang.add(e.getNgayLap().getMonth());
        }
        // Tính tổng doanh thu của từng ngày        
        ArrayList<Cus> dtday = new ArrayList();
        for (var ngay : SetNgay) {
            double dt = 0.0d;
            // System.out.println(ngay.toString());
            for (int j = 0; j < listhd.size(); ++j) {
                if (ngay.toString().equals(listhd.get(j).getNgayLap().toString())) {
                    dt = dt + listhd.get(j).getTongTien().doubleValue();
                }
            }
            Cus custemp = new Cus();
            custemp.doanhthu = dt;
            custemp.ngay = ngay;
            dtday.add(custemp);
        }

        Collections.sort(dtday, new Comparator<Cus>() {
            public int compare(Cus cus1, Cus cus2) {
                return cus1.ngay.compareTo(cus2.ngay);
            }
        });

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (dtday != null && !dtday.isEmpty()) {
            for (Cus m : dtday) {
                dataset.setValue(m.doanhthu, "Doanh thu theo ngày", (m.ngay));
            }
        }
        // Tạo biểu đồ cột
        JFreeChart chart = ChartFactory.createBarChart("Thống kê doanh thu theo ngày", "Ngày", "Doanh Thu (VND)", dataset, PlotOrientation.VERTICAL, false, true, false);
        // Lấy đối tượng CategoryPlot từ biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        // Thiết lập màu cho cột
        GradientPaint gp = new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.green
        );
        plot.getRenderer().setSeriesPaint(0, gp);
        // Thiết lập màu nền cho biểu đồ
        plot.setBackgroundPaint(new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.gray
        ));
        // Thiết lập màu nền cho biểu đồ cột
        plot.setRangeGridlinePaint(new Color(0, 0, 0, 0));
        // Hiển thị biểu đồ trong JFrame
        ChartFrame frame = new ChartFrame("Doanh thu", chart);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(800, 600);
    }//GEN-LAST:event_tktngayMouseClicked

    private void tktthangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tktthangMouseClicked
        // TODO add your handling code here:

        Set<Date> SetNgay = new HashSet<>(); // 
        Set<Integer> SetThang = new HashSet<>();

        for (Hoadon e : listhd) {
            SetNgay.add(e.getNgayLap());
        }

        for (Hoadon e : listhd) {
            SetThang.add(e.getNgayLap().getMonth());
        }
        // Tính tổng doanh thu của từng ngày        
        ArrayList<Cus> dtday = new ArrayList();
        for (var ngay : SetNgay) {
            double dt = 0.0d;
            // System.out.println(ngay.toString());
            for (int j = 0; j < listhd.size(); ++j) {
                if (ngay.toString().equals(listhd.get(j).getNgayLap().toString())) {
                    dt = dt + listhd.get(j).getTongTien().doubleValue();
                }
            }
            Cus custemp = new Cus();
            custemp.doanhthu = dt;
            custemp.ngay = ngay;
            dtday.add(custemp);
        }
        // Tính tổng doanh thu của từng tháng 
        ArrayList<CusMonth> month = new ArrayList(12);
        for (int itmon : SetThang) {
            double dttheothang = 0.0d;
            for (Cus doanhthutheongay : dtday) {
                if (itmon == doanhthutheongay.ngay.getMonth()) {
                    dttheothang = dttheothang + doanhthutheongay.doanhthu;
                }
            }
            CusMonth cusMonth = new CusMonth();
            cusMonth.doanhthu = dttheothang;
            cusMonth.thang = itmon + 1;
            month.add(cusMonth);
        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (month != null && !month.isEmpty()) {
            for (CusMonth m : month) {
                dataset.setValue(m.doanhthu, "Doanh thu theo tháng", Integer.toString(m.thang));
            }
        }
        // Tạo biểu đồ cột
        JFreeChart chart = ChartFactory.createBarChart("Thống kê doanh thu theo tháng", "Tháng", "Doanh Thu (VND)", dataset, PlotOrientation.VERTICAL, false, true, false);
        // Lấy đối tượng CategoryPlot từ biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        // Thiết lập màu cho cột
        GradientPaint gp = new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.green
        );
        plot.getRenderer().setSeriesPaint(0, gp);
        // Thiết lập màu nền cho biểu đồ
        plot.setBackgroundPaint(new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.gray
        ));
        // Thiết lập màu nền cho biểu đồ cột
        plot.setRangeGridlinePaint(new Color(0, 0, 0, 0));
        // Hiển thị biểu đồ trong JFrame
        ChartFrame frame = new ChartFrame("Doanh thu", chart);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(800, 600);
    }//GEN-LAST:event_tktthangMouseClicked

    private void tkspbanchayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tkspbanchayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tkspbanchayMouseClicked

    private void tkspBanChayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tkspBanChayMouseClicked
        // TODO add your handling code here: 
        // Sắp xếp tháng theo thứ tự tăng dần
        Collections.sort(results, Comparator.comparingInt((Object[] o) -> (int) o[0])
                .thenComparingInt(o -> ((Number) o[2]).intValue())
                .reversed());

        int[] monthOrder = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};

        Map<Integer, String> giayMap = new HashMap<>();

        for (Chitiethoadon cthd : dscthd) {
            int idGiay = cthd.getId().getIdgiay();
            for (Sanpham sanPham : dssp) {
                if (sanPham.getIdgiay() == idGiay) {
                    giayMap.put(idGiay, sanPham.getTen());
                    break;
                }
            }
        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int month : monthOrder) {
            for (Object[] result : results) {
                int resultMonth = (int) result[0];
                if (resultMonth == month) {
                    int idGiay = (int) result[1];
                    int soLuong = ((Number) result[2]).intValue();
                    String tenGiay = giayMap.get(idGiay);
                    dataset.addValue(soLuong, tenGiay, "Tháng " + month);
                }
            }
        }
        // Tạo biểu đồ cột
        JFreeChart chart = ChartFactory.createBarChart(
                "Sản phẩm bán chạy nhất theo tháng",
                "Tháng",
                "Số lượng",
                dataset,
                PlotOrientation.VERTICAL,
                false,
                true,
                false);
        // Lấy đối tượng CategoryPlot từ biểu đồ
        CategoryPlot plot = chart.getCategoryPlot();
        // Định nghĩa CategoryItemLabelGenerator để hiển thị tên giày trên mỗi cột
        CategoryItemLabelGenerator generator = new StandardCategoryItemLabelGenerator() {
            @Override
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                String label = dataset.getColumnKey(column).toString(); // Lấy tên cột (IDGiay)
                if (label.startsWith("IDGiay ")) {
                    int idGiay = Integer.parseInt(label.replace("IDGiay ", "")); // Chuyển đổi thành IDGiay
                    String tenGiay = giayMap.get(idGiay); // Lấy tên giày từ ánh xạ giày
                    return tenGiay;
                }
                return super.generateLabel(dataset, row, column); // Sử dụng phương thức mặc định để hiển thị tên cột
            }
        };

        // Thiết lập CategoryItemLabelGenerator cho CategoryPlot của biểu đồ
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesItemLabelGenerator(0, generator);
        renderer.setSeriesItemLabelsVisible(0, true);

        // Thiết lập màu cho cột
        GradientPaint gp = new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.green
        );
        plot.getRenderer().setSeriesPaint(0, gp);
        // Thiết lập màu nền cho biểu đồ
        plot.setBackgroundPaint(new GradientPaint(
                0.0f, 0.0f, Color.white,
                0.0f, 0.0f, Color.gray
        ));
        // Thiết lập màu nền cho biểu đồ cột
        plot.setRangeGridlinePaint(new Color(0, 0, 0, 0));
        // Hiển thị biểu đồ trong JFrame
        ChartFrame frame = new ChartFrame("Sản phẩm bán chạy nhất theo tháng", chart);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(800, 600);
    }//GEN-LAST:event_tkspBanChayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeFormOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeFormOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeFormOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeFormOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeFormOld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tkdt;
    private javax.swing.JLabel tkspBanChay;
    private javax.swing.JPanel tkspbanchay;
    private javax.swing.JPanel tktngay;
    private javax.swing.JPanel tktthang;
    // End of variables declaration//GEN-END:variables
}
