package entity1;
// Generated Mar 24, 2023, 8:47:13 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietphieunhap generated by hbm2java
 */
@Entity
@Table(name = "chitietphieunhap", catalog = "cuahangbangiay")
public class Chitietphieunhap implements java.io.Serializable {

	private ChitietphieunhapId id;
	private Giay giay;
	private Phieunhap phieunhap;

	public Chitietphieunhap() {
	}

	public Chitietphieunhap(ChitietphieunhapId id) {
		this.id = id;
	}

	public Chitietphieunhap(ChitietphieunhapId id, Giay giay, Phieunhap phieunhap) {
		this.id = id;
		this.giay = giay;
		this.phieunhap = phieunhap;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idphieuNhap", column = @Column(name = "IDPhieuNhap")),
			@AttributeOverride(name = "idgiay", column = @Column(name = "IDGiay")),
			@AttributeOverride(name = "gia", column = @Column(name = "Gia", scale = 4)),
			@AttributeOverride(name = "soluong", column = @Column(name = "Soluong")) })
	public ChitietphieunhapId getId() {
		return this.id;
	}

	public void setId(ChitietphieunhapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDGiay", insertable = false, updatable = false)
	public Giay getGiay() {
		return this.giay;
	}

	public void setGiay(Giay giay) {
		this.giay = giay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPhieuNhap", insertable = false, updatable = false)
	public Phieunhap getPhieunhap() {
		return this.phieunhap;
	}

	public void setPhieunhap(Phieunhap phieunhap) {
		this.phieunhap = phieunhap;
	}

}
