package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

/**
 * ChitiethoadonId generated by hbm2java
 */
public class ChitiethoadonId implements java.io.Serializable {

	private Integer idhoaDon;
	private Integer idgiay;
	private Integer soLuong;

	public ChitiethoadonId() {
	}

	public ChitiethoadonId(Integer idhoaDon, Integer idgiay, Integer soLuong) {
		this.idhoaDon = idhoaDon;
		this.idgiay = idgiay;
		this.soLuong = soLuong;
	}

	public Integer getIdhoaDon() {
		return this.idhoaDon;
	}

	public void setIdhoaDon(Integer idhoaDon) {
		this.idhoaDon = idhoaDon;
	}

	public Integer getIdgiay() {
		return this.idgiay;
	}

	public void setIdgiay(Integer idgiay) {
		this.idgiay = idgiay;
	}

	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitiethoadonId))
			return false;
		ChitiethoadonId castOther = (ChitiethoadonId) other;

		return ((this.getIdhoaDon() == castOther.getIdhoaDon()) || (this.getIdhoaDon() != null
				&& castOther.getIdhoaDon() != null && this.getIdhoaDon().equals(castOther.getIdhoaDon())))
				&& ((this.getIdgiay() == castOther.getIdgiay()) || (this.getIdgiay() != null
						&& castOther.getIdgiay() != null && this.getIdgiay().equals(castOther.getIdgiay())))
				&& ((this.getSoLuong() == castOther.getSoLuong()) || (this.getSoLuong() != null
						&& castOther.getSoLuong() != null && this.getSoLuong().equals(castOther.getSoLuong())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdhoaDon() == null ? 0 : this.getIdhoaDon().hashCode());
		result = 37 * result + (getIdgiay() == null ? 0 : this.getIdgiay().hashCode());
		result = 37 * result + (getSoLuong() == null ? 0 : this.getSoLuong().hashCode());
		return result;
	}

}
