package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietphieunhapId generated by hbm2java
 */
@Embeddable
public class ChitietphieunhapId implements java.io.Serializable {

	private Integer idphieuNhap;
	private Integer idgiay;
	private BigDecimal gia;
	private Integer soluong;

	public ChitietphieunhapId() {
	}

	public ChitietphieunhapId(Integer idphieuNhap, Integer idgiay, BigDecimal gia, Integer soluong) {
		this.idphieuNhap = idphieuNhap;
		this.idgiay = idgiay;
		this.gia = gia;
		this.soluong = soluong;
	}

	@Column(name = "IDPhieuNhap")
	public Integer getIdphieuNhap() {
		return this.idphieuNhap;
	}

	public void setIdphieuNhap(Integer idphieuNhap) {
		this.idphieuNhap = idphieuNhap;
	}

	@Column(name = "IDGiay")
	public Integer getIdgiay() {
		return this.idgiay;
	}

	public void setIdgiay(Integer idgiay) {
		this.idgiay = idgiay;
	}

	@Column(name = "Gia", scale = 4)
	public BigDecimal getGia() {
		return this.gia;
	}

	public void setGia(BigDecimal gia) {
		this.gia = gia;
	}

	@Column(name = "Soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitietphieunhapId))
			return false;
		ChitietphieunhapId castOther = (ChitietphieunhapId) other;

		return ((this.getIdphieuNhap() == castOther.getIdphieuNhap()) || (this.getIdphieuNhap() != null
				&& castOther.getIdphieuNhap() != null && this.getIdphieuNhap().equals(castOther.getIdphieuNhap())))
				&& ((this.getIdgiay() == castOther.getIdgiay()) || (this.getIdgiay() != null
						&& castOther.getIdgiay() != null && this.getIdgiay().equals(castOther.getIdgiay())))
				&& ((this.getGia() == castOther.getGia()) || (this.getGia() != null && castOther.getGia() != null
						&& this.getGia().equals(castOther.getGia())))
				&& ((this.getSoluong() == castOther.getSoluong()) || (this.getSoluong() != null
						&& castOther.getSoluong() != null && this.getSoluong().equals(castOther.getSoluong())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdphieuNhap() == null ? 0 : this.getIdphieuNhap().hashCode());
		result = 37 * result + (getIdgiay() == null ? 0 : this.getIdgiay().hashCode());
		result = 37 * result + (getGia() == null ? 0 : this.getGia().hashCode());
		result = 37 * result + (getSoluong() == null ? 0 : this.getSoluong().hashCode());
		return result;
	}

}
