package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon implements java.io.Serializable {

	private ChitiethoadonId id;
	private Giay giay;
	private Hoadon hoadon;

	public Chitiethoadon() {
	}

	public Chitiethoadon(ChitiethoadonId id) {
		this.id = id;
	}

	public Chitiethoadon(ChitiethoadonId id, Giay giay, Hoadon hoadon) {
		this.id = id;
		this.giay = giay;
		this.hoadon = hoadon;
	}

	public ChitiethoadonId getId() {
		return this.id;
	}

	public void setId(ChitiethoadonId id) {
		this.id = id;
	}

	public Giay getGiay() {
		return this.giay;
	}

	public void setGiay(Giay giay) {
		this.giay = giay;
	}

	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

}
