package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Giay generated by hbm2java
 */
@Entity
@Table(name = "giay", catalog = "cuahangbangiay")
public class Giay implements java.io.Serializable {

	private int idgiay;
	private Phanloai phanloai;
	private String ten;
	private Double size;
	private String mau;
	private String vatLieu;
	private byte[] anh;
	private BigDecimal giaBan;
	private String themMoTa;
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);
	private Set<Chitietphieunhap> chitietphieunhaps = new HashSet<Chitietphieunhap>(0);

	public Giay() {
	}

	public Giay(int idgiay) {
		this.idgiay = idgiay;
	}

	public Giay(int idgiay, Phanloai phanloai, String ten, Double size, String mau, String vatLieu, byte[] anh,
			BigDecimal giaBan, String themMoTa, Set<Chitiethoadon> chitiethoadons,
			Set<Chitietphieunhap> chitietphieunhaps) {
		this.idgiay = idgiay;
		this.phanloai = phanloai;
		this.ten = ten;
		this.size = size;
		this.mau = mau;
		this.vatLieu = vatLieu;
		this.anh = anh;
		this.giaBan = giaBan;
		this.themMoTa = themMoTa;
		this.chitiethoadons = chitiethoadons;
		this.chitietphieunhaps = chitietphieunhaps;
	}

	@Id

	@Column(name = "IDGiay", unique = true, nullable = false)
	public int getIdgiay() {
		return this.idgiay;
	}

	public void setIdgiay(int idgiay) {
		this.idgiay = idgiay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPhanLoai")
	public Phanloai getPhanloai() {
		return this.phanloai;
	}

	public void setPhanloai(Phanloai phanloai) {
		this.phanloai = phanloai;
	}

	@Column(name = "Ten", length = 0)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "Size", precision = 22, scale = 0)
	public Double getSize() {
		return this.size;
	}

	public void setSize(Double size) {
		this.size = size;
	}

	@Column(name = "Mau", length = 10)
	public String getMau() {
		return this.mau;
	}

	public void setMau(String mau) {
		this.mau = mau;
	}

	@Column(name = "VatLieu", length = 0)
	public String getVatLieu() {
		return this.vatLieu;
	}

	public void setVatLieu(String vatLieu) {
		this.vatLieu = vatLieu;
	}

	@Column(name = "Anh")
	public byte[] getAnh() {
		return this.anh;
	}

	public void setAnh(byte[] anh) {
		this.anh = anh;
	}

	@Column(name = "GiaBan", scale = 4)
	public BigDecimal getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(BigDecimal giaBan) {
		this.giaBan = giaBan;
	}

	@Column(name = "ThemMoTa", length = 0)
	public String getThemMoTa() {
		return this.themMoTa;
	}

	public void setThemMoTa(String themMoTa) {
		this.themMoTa = themMoTa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giay")
	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giay")
	public Set<Chitietphieunhap> getChitietphieunhaps() {
		return this.chitietphieunhaps;
	}

	public void setChitietphieunhaps(Set<Chitietphieunhap> chitietphieunhaps) {
		this.chitietphieunhaps = chitietphieunhaps;
	}

}
