package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", catalog = "cuahangbangiay")
public class Hoadon implements java.io.Serializable {

	private int idhoaDon;
	private Khachhang khachhang;
	private Nhacungcap nhacungcap;
	private Nhanvien nhanvien;
	private Date ngayLap;
	private BigDecimal tongTien;
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

	public Hoadon() {
	}

	public Hoadon(int idhoaDon) {
		this.idhoaDon = idhoaDon;
	}

	public Hoadon(int idhoaDon, Khachhang khachhang, Nhacungcap nhacungcap, Nhanvien nhanvien, Date ngayLap,
			BigDecimal tongTien, Set<Chitiethoadon> chitiethoadons) {
		this.idhoaDon = idhoaDon;
		this.khachhang = khachhang;
		this.nhacungcap = nhacungcap;
		this.nhanvien = nhanvien;
		this.ngayLap = ngayLap;
		this.tongTien = tongTien;
		this.chitiethoadons = chitiethoadons;
	}

	@Id

	@Column(name = "IDHoaDon", unique = true, nullable = false)
	public int getIdhoaDon() {
		return this.idhoaDon;
	}

	public void setIdhoaDon(int idhoaDon) {
		this.idhoaDon = idhoaDon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDKhachHang")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNhaCungCap")
	public Nhacungcap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(Nhacungcap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNhanVien")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayLap", length = 10)
	public Date getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(Date ngayLap) {
		this.ngayLap = ngayLap;
	}

	@Column(name = "TongTien", scale = 4)
	public BigDecimal getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(BigDecimal tongTien) {
		this.tongTien = tongTien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

}
