package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", catalog = "cuahangbangiay")
public class Khachhang implements java.io.Serializable {

	private int idkhachHang;
	private The the;
	private Date ngayLapThe;
	private String hoVaTen;
	private String gioiTinh;
	private Date ngaySinh;
	private String diaChi;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Khachhang() {
	}

	public Khachhang(int idkhachHang) {
		this.idkhachHang = idkhachHang;
	}

	public Khachhang(int idkhachHang, The the, Date ngayLapThe, String hoVaTen, String gioiTinh, Date ngaySinh,
			String diaChi, Set<Hoadon> hoadons) {
		this.idkhachHang = idkhachHang;
		this.the = the;
		this.ngayLapThe = ngayLapThe;
		this.hoVaTen = hoVaTen;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "IDKhachHang", unique = true, nullable = false)
	public int getIdkhachHang() {
		return this.idkhachHang;
	}

	public void setIdkhachHang(int idkhachHang) {
		this.idkhachHang = idkhachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDThe")
	public The getThe() {
		return this.the;
	}

	public void setThe(The the) {
		this.the = the;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayLapThe", length = 10)
	public Date getNgayLapThe() {
		return this.ngayLapThe;
	}

	public void setNgayLapThe(Date ngayLapThe) {
		this.ngayLapThe = ngayLapThe;
	}

	@Column(name = "HoVaTen", length = 100)
	public String getHoVaTen() {
		return this.hoVaTen;
	}

	public void setHoVaTen(String hoVaTen) {
		this.hoVaTen = hoVaTen;
	}

	@Column(name = "GioiTinh", length = 100)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "DiaChi", length = 100)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachhang")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
