package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Loainv generated by hbm2java
 */
public class Loainv implements java.io.Serializable {

	private Integer idloai;
	private String tenLoai;
	private String ghiChu;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Loainv() {
	}

	public Loainv(String tenLoai, String ghiChu, Set<Nhanvien> nhanviens) {
		this.tenLoai = tenLoai;
		this.ghiChu = ghiChu;
		this.nhanviens = nhanviens;
	}

	public Integer getIdloai() {
		return this.idloai;
	}

	public void setIdloai(Integer idloai) {
		this.idloai = idloai;
	}

	public String getTenLoai() {
		return this.tenLoai;
	}

	public void setTenLoai(String tenLoai) {
		this.tenLoai = tenLoai;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
