package entity1;
// Generated Mar 24, 2023, 8:47:13 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loainv generated by hbm2java
 */
@Entity
@Table(name = "loainv", catalog = "cuahangbangiay")
public class Loainv implements java.io.Serializable {

	private int idloai;
	private String tenLoai;
	private String ghiChu;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Loainv() {
	}

	public Loainv(int idloai) {
		this.idloai = idloai;
	}

	public Loainv(int idloai, String tenLoai, String ghiChu, Set<Nhanvien> nhanviens) {
		this.idloai = idloai;
		this.tenLoai = tenLoai;
		this.ghiChu = ghiChu;
		this.nhanviens = nhanviens;
	}

	@Id

	@Column(name = "IDLoai", unique = true, nullable = false)
	public int getIdloai() {
		return this.idloai;
	}

	public void setIdloai(int idloai) {
		this.idloai = idloai;
	}

	@Column(name = "TenLoai", length = 50)
	public String getTenLoai() {
		return this.tenLoai;
	}

	public void setTenLoai(String tenLoai) {
		this.tenLoai = tenLoai;
	}

	@Column(name = "GhiChu", length = 50)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loainv")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
