package entity1;
// Generated Mar 24, 2023, 8:47:13 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manhinh generated by hbm2java
 */
@Entity
@Table(name = "manhinh", catalog = "cuahangbangiay")
public class Manhinh implements java.io.Serializable {

	private int idmanHinh;
	private String tenManHinh;
	private String ghiChu;
	private Set<Phanquyen> phanquyens = new HashSet<Phanquyen>(0);

	public Manhinh() {
	}

	public Manhinh(int idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	public Manhinh(int idmanHinh, String tenManHinh, String ghiChu, Set<Phanquyen> phanquyens) {
		this.idmanHinh = idmanHinh;
		this.tenManHinh = tenManHinh;
		this.ghiChu = ghiChu;
		this.phanquyens = phanquyens;
	}

	@Id

	@Column(name = "IDManHinh", unique = true, nullable = false)
	public int getIdmanHinh() {
		return this.idmanHinh;
	}

	public void setIdmanHinh(int idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	@Column(name = "TenManHinh", length = 0)
	public String getTenManHinh() {
		return this.tenManHinh;
	}

	public void setTenManHinh(String tenManHinh) {
		this.tenManHinh = tenManHinh;
	}

	@Column(name = "GhiChu", length = 0)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manhinh")
	public Set<Phanquyen> getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set<Phanquyen> phanquyens) {
		this.phanquyens = phanquyens;
	}

}
