package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Manhinh generated by hbm2java
 */
public class Manhinh implements java.io.Serializable {

	private Integer idmanHinh;
	private String tenManHinh;
	private String ghiChu;
	private Set phanquyens = new HashSet(0);

	public Manhinh() {
	}

	public Manhinh(String tenManHinh, String ghiChu, Set phanquyens) {
		this.tenManHinh = tenManHinh;
		this.ghiChu = ghiChu;
		this.phanquyens = phanquyens;
	}

	public Integer getIdmanHinh() {
		return this.idmanHinh;
	}

	public void setIdmanHinh(Integer idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	public String getTenManHinh() {
		return this.tenManHinh;
	}

	public void setTenManHinh(String tenManHinh) {
		this.tenManHinh = tenManHinh;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public Set getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set phanquyens) {
		this.phanquyens = phanquyens;
	}

}
