package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Manhinh generated by hbm2java
 */
public class Manhinh implements java.io.Serializable {

	private int idmanHinh;
	private String tenManHinh;
	private String ghiChu;
	private Set phanquyens = new HashSet(0);

	public Manhinh() {
	}

	public Manhinh(int idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	public Manhinh(int idmanHinh, String tenManHinh, String ghiChu, Set phanquyens) {
		this.idmanHinh = idmanHinh;
		this.tenManHinh = tenManHinh;
		this.ghiChu = ghiChu;
		this.phanquyens = phanquyens;
	}

	public int getIdmanHinh() {
		return this.idmanHinh;
	}

	public void setIdmanHinh(int idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	public String getTenManHinh() {
		return this.tenManHinh;
	}

	public void setTenManHinh(String tenManHinh) {
		this.tenManHinh = tenManHinh;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public Set getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set phanquyens) {
		this.phanquyens = phanquyens;
	}

}
