package entity1;
// Generated Apr 13, 2023, 8:33:14 PM by Hibernate Tools 5.6.12.Final

/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung implements java.io.Serializable {

	private Integer idnguoiDung;
	private Integer idnhanVien;
	private String tenDangNhap;
	private String tenTaiKhoan;
	private String matKhau;
	

	public Nguoidung() {
	}

	public Nguoidung(Integer idnhanVien, String tenDangNhap, String tenTaiKhoan, String matKhau) {
		this.idnhanVien = idnhanVien;
		this.tenDangNhap = tenDangNhap;
		this.tenTaiKhoan = tenTaiKhoan;
		this.matKhau = matKhau;
		
	}

	public Integer getIdnguoiDung() {
		return this.idnguoiDung;
	}

	public void setIdnguoiDung(Integer idnguoiDung) {
		this.idnguoiDung = idnguoiDung;
	}

	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public String getTenTaiKhoan() {
		return this.tenTaiKhoan;
	}

	public void setTenTaiKhoan(String tenTaiKhoan) {
		this.tenTaiKhoan = tenTaiKhoan;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	

}
