package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap implements java.io.Serializable {

	private int idnhaCungCap;
	private String ten;
	private Integer sdt;
	private String email;
	private Date thoiGianHopTac;
	private Set hoadons = new HashSet(0);

	public Nhacungcap() {
	}

	public Nhacungcap(int idnhaCungCap) {
		this.idnhaCungCap = idnhaCungCap;
	}

	public Nhacungcap(int idnhaCungCap, String ten, Integer sdt, String email, Date thoiGianHopTac, Set hoadons) {
		this.idnhaCungCap = idnhaCungCap;
		this.ten = ten;
		this.sdt = sdt;
		this.email = email;
		this.thoiGianHopTac = thoiGianHopTac;
		this.hoadons = hoadons;
	}

	public int getIdnhaCungCap() {
		return this.idnhaCungCap;
	}

	public void setIdnhaCungCap(int idnhaCungCap) {
		this.idnhaCungCap = idnhaCungCap;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getThoiGianHopTac() {
		return this.thoiGianHopTac;
	}

	public void setThoiGianHopTac(Date thoiGianHopTac) {
		this.thoiGianHopTac = thoiGianHopTac;
	}

	public Set getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set hoadons) {
		this.hoadons = hoadons;
	}

}
