package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name = "nhacungcap", catalog = "cuahangbangiay")
public class Nhacungcap implements java.io.Serializable {

	private int idnhaCungCap;
	private String ten;
	private Integer sdt;
	private String email;
	private Date thoiGianHopTac;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Nhacungcap() {
	}

	public Nhacungcap(int idnhaCungCap) {
		this.idnhaCungCap = idnhaCungCap;
	}

	public Nhacungcap(int idnhaCungCap, String ten, Integer sdt, String email, Date thoiGianHopTac,
			Set<Hoadon> hoadons) {
		this.idnhaCungCap = idnhaCungCap;
		this.ten = ten;
		this.sdt = sdt;
		this.email = email;
		this.thoiGianHopTac = thoiGianHopTac;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "IDNhaCungCap", unique = true, nullable = false)
	public int getIdnhaCungCap() {
		return this.idnhaCungCap;
	}

	public void setIdnhaCungCap(int idnhaCungCap) {
		this.idnhaCungCap = idnhaCungCap;
	}

	@Column(name = "Ten", length = 0)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "SDT")
	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Email", length = 0)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ThoiGianHopTac", length = 10)
	public Date getThoiGianHopTac() {
		return this.thoiGianHopTac;
	}

	public void setThoiGianHopTac(Date thoiGianHopTac) {
		this.thoiGianHopTac = thoiGianHopTac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhacungcap")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
