package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nhanvienquanlykho generated by hbm2java
 */
@Entity
@Table(name = "nhanvienquanlykho", catalog = "cuahangbangiay")
public class Nhanvienquanlykho implements java.io.Serializable {

	private NhanvienquanlykhoId id;
	private Nhanvien nhanvien;

	public Nhanvienquanlykho() {
	}

	public Nhanvienquanlykho(NhanvienquanlykhoId id) {
		this.id = id;
	}

	public Nhanvienquanlykho(NhanvienquanlykhoId id, Nhanvien nhanvien) {
		this.id = id;
		this.nhanvien = nhanvien;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idnhanVien", column = @Column(name = "IDNhanVien")),
			@AttributeOverride(name = "soNgayLam", column = @Column(name = "SoNgayLam")) })
	public NhanvienquanlykhoId getId() {
		return this.id;
	}

	public void setId(NhanvienquanlykhoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNhanVien", insertable = false, updatable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

}
