package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien implements java.io.Serializable {

	private Integer idnhanVien;
	private String hoVaTen;
	private Integer sdt;
	private Date ngaySinh;
	private String email;
	private Double luong;
	private byte[] anh;
	private Set<Nguoidung> nguoidungs = new HashSet<Nguoidung>(0);

	public Nhanvien() {
	}

    @Override
    public String toString() {
        return "Nhanvien{" + "idnhanVien=" + idnhanVien + ", hoVaTen=" + hoVaTen + ", sdt=" + sdt + ", ngaySinh=" + ngaySinh + ", email=" + email + ", luong=" + luong + '}';
    }

   
        

	public Nhanvien( String hoVaTen, Integer sdt, Date ngaySinh, String email, Double luong, byte[] anh,
			Set<Nguoidung> nguoidungs) {
		
		this.hoVaTen = hoVaTen;
		this.sdt = sdt;
		this.ngaySinh = ngaySinh;
		this.email = email;
		this.luong = luong;
		this.anh = anh;
		this.nguoidungs = nguoidungs;
	}

	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	

	public String getHoVaTen() {
		return this.hoVaTen;
	}

	public void setHoVaTen(String hoVaTen) {
		this.hoVaTen = hoVaTen;
	}

	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getLuong() {
		return this.luong;
	}

	public void setLuong(Double luong) {
		this.luong = luong;
	}

	public byte[] getAnh() {
		return this.anh;
	}

	public void setAnh(byte[] anh) {
		this.anh = anh;
	}

	public Set<Nguoidung> getNguoidungs() {
		return this.nguoidungs;
	}

	public void setNguoidungs(Set<Nguoidung> nguoidungs) {
		this.nguoidungs = nguoidungs;
	}

}
