package entity1;
// Generated Mar 24, 2023, 8:47:13 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien", catalog = "cuahangbangiay", uniqueConstraints = @UniqueConstraint(columnNames = "SDT"))
public class Nhanvien implements java.io.Serializable {

	private int idnhanVien;
	private Loainv loainv;
	private String hoVaTen;
	private Integer sdt;
	private Date ngaySinh;
	private String email;
	private Double luong;
	private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);
	private Set<Nguoidung> nguoidungs = new HashSet<Nguoidung>(0);

	public Nhanvien() {
	}

	public Nhanvien(int idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	public Nhanvien(int idnhanVien, Loainv loainv, String hoVaTen, Integer sdt, Date ngaySinh, String email,
			Double luong, Set<Phieunhap> phieunhaps, Set<Hoadon> hoadons, Set<Nguoidung> nguoidungs) {
		this.idnhanVien = idnhanVien;
		this.loainv = loainv;
		this.hoVaTen = hoVaTen;
		this.sdt = sdt;
		this.ngaySinh = ngaySinh;
		this.email = email;
		this.luong = luong;
		this.phieunhaps = phieunhaps;
		this.hoadons = hoadons;
		this.nguoidungs = nguoidungs;
	}

	@Id

	@Column(name = "IDNhanVien", unique = true, nullable = false)
	public int getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(int idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDLoai")
	public Loainv getLoainv() {
		return this.loainv;
	}

	public void setLoainv(Loainv loainv) {
		this.loainv = loainv;
	}

	@Column(name = "HoVaTen", length = 0)
	public String getHoVaTen() {
		return this.hoVaTen;
	}

	public void setHoVaTen(String hoVaTen) {
		this.hoVaTen = hoVaTen;
	}

	@Column(name = "SDT", unique = true)
	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Luong", precision = 22, scale = 0)
	public Double getLuong() {
		return this.luong;
	}

	public void setLuong(Double luong) {
		this.luong = luong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Phieunhap> getPhieunhaps() {
		return this.phieunhaps;
	}

	public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
		this.phieunhaps = phieunhaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Nguoidung> getNguoidungs() {
		return this.nguoidungs;
	}

	public void setNguoidungs(Set<Nguoidung> nguoidungs) {
		this.nguoidungs = nguoidungs;
	}

}
