package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NhanvienbanhangId generated by hbm2java
 */
@Embeddable
public class NhanvienbanhangId implements java.io.Serializable {

	private Integer idnhanVien;
	private Double soGioLam;

	public NhanvienbanhangId() {
	}

	public NhanvienbanhangId(Integer idnhanVien, Double soGioLam) {
		this.idnhanVien = idnhanVien;
		this.soGioLam = soGioLam;
	}

	@Column(name = "IDNhanVien")
	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	@Column(name = "SoGioLam", precision = 22, scale = 0)
	public Double getSoGioLam() {
		return this.soGioLam;
	}

	public void setSoGioLam(Double soGioLam) {
		this.soGioLam = soGioLam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NhanvienbanhangId))
			return false;
		NhanvienbanhangId castOther = (NhanvienbanhangId) other;

		return ((this.getIdnhanVien() == castOther.getIdnhanVien()) || (this.getIdnhanVien() != null
				&& castOther.getIdnhanVien() != null && this.getIdnhanVien().equals(castOther.getIdnhanVien())))
				&& ((this.getSoGioLam() == castOther.getSoGioLam()) || (this.getSoGioLam() != null
						&& castOther.getSoGioLam() != null && this.getSoGioLam().equals(castOther.getSoGioLam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdnhanVien() == null ? 0 : this.getIdnhanVien().hashCode());
		result = 37 * result + (getSoGioLam() == null ? 0 : this.getSoGioLam().hashCode());
		return result;
	}

}
