package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien implements java.io.Serializable {

	private Integer idnhanVien;
	private Loainv loainv;
	private String hoVaTen;
	private Integer sdt;
	private Date ngaySinh;
	private String email;
	private Double luong;
	private Set nguoidungs = new HashSet(0);

	public Nhanvien() {
	}

	public Nhanvien(Loainv loainv, String hoVaTen, Integer sdt, Date ngaySinh, String email, Double luong,
			Set nguoidungs) {
		this.loainv = loainv;
		this.hoVaTen = hoVaTen;
		this.sdt = sdt;
		this.ngaySinh = ngaySinh;
		this.email = email;
		this.luong = luong;
		this.nguoidungs = nguoidungs;
	}

	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	public Loainv getLoainv() {
		return this.loainv;
	}

	public void setLoainv(Loainv loainv) {
		this.loainv = loainv;
	}

	public String getHoVaTen() {
		return this.hoVaTen;
	}

	public void setHoVaTen(String hoVaTen) {
		this.hoVaTen = hoVaTen;
	}

	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getLuong() {
		return this.luong;
	}

	public void setLuong(Double luong) {
		this.luong = luong;
	}

	public Set getNguoidungs() {
		return this.nguoidungs;
	}

	public void setNguoidungs(Set nguoidungs) {
		this.nguoidungs = nguoidungs;
	}

}
