package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nhanvienbanhang generated by hbm2java
 */
@Entity
@Table(name = "nhanvienbanhang", catalog = "cuahangbangiay")
public class Nhanvienbanhang implements java.io.Serializable {

	private NhanvienbanhangId id;
	private Nhanvien nhanvien;

	public Nhanvienbanhang() {
	}

	public Nhanvienbanhang(NhanvienbanhangId id) {
		this.id = id;
	}

	public Nhanvienbanhang(NhanvienbanhangId id, Nhanvien nhanvien) {
		this.id = id;
		this.nhanvien = nhanvien;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idnhanVien", column = @Column(name = "IDNhanVien")),
			@AttributeOverride(name = "soGioLam", column = @Column(name = "SoGioLam", precision = 22, scale = 0)) })
	public NhanvienbanhangId getId() {
		return this.id;
	}

	public void setId(NhanvienbanhangId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNhanVien", insertable = false, updatable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

}
