package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NhanvienquanlykhoId generated by hbm2java
 */
@Embeddable
public class NhanvienquanlykhoId implements java.io.Serializable {

	private Integer idnhanVien;
	private Integer soNgayLam;

	public NhanvienquanlykhoId() {
	}

	public NhanvienquanlykhoId(Integer idnhanVien, Integer soNgayLam) {
		this.idnhanVien = idnhanVien;
		this.soNgayLam = soNgayLam;
	}

	@Column(name = "IDNhanVien")
	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	@Column(name = "SoNgayLam")
	public Integer getSoNgayLam() {
		return this.soNgayLam;
	}

	public void setSoNgayLam(Integer soNgayLam) {
		this.soNgayLam = soNgayLam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NhanvienquanlykhoId))
			return false;
		NhanvienquanlykhoId castOther = (NhanvienquanlykhoId) other;

		return ((this.getIdnhanVien() == castOther.getIdnhanVien()) || (this.getIdnhanVien() != null
				&& castOther.getIdnhanVien() != null && this.getIdnhanVien().equals(castOther.getIdnhanVien())))
				&& ((this.getSoNgayLam() == castOther.getSoNgayLam()) || (this.getSoNgayLam() != null
						&& castOther.getSoNgayLam() != null && this.getSoNgayLam().equals(castOther.getSoNgayLam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdnhanVien() == null ? 0 : this.getIdnhanVien().hashCode());
		result = 37 * result + (getSoNgayLam() == null ? 0 : this.getSoNgayLam().hashCode());
		return result;
	}

}
