package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

/**
 * Nhomvanguoidung generated by hbm2java
 */
public class Nhomvanguoidung implements java.io.Serializable {

	private NhomvanguoidungId id;
	private Nguoidung nguoidung;

	public Nhomvanguoidung() {
	}

	public Nhomvanguoidung(NhomvanguoidungId id) {
		this.id = id;
	}

	public Nhomvanguoidung(NhomvanguoidungId id, Nguoidung nguoidung) {
		this.id = id;
		this.nguoidung = nguoidung;
	}

	public NhomvanguoidungId getId() {
		return this.id;
	}

	public void setId(NhomvanguoidungId id) {
		this.id = id;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

}
