package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

/**
 * Nhomvanguoidung generated by hbm2java
 */
public class Nhomvanguoidung implements java.io.Serializable {

	private NhomvanguoidungId id;
	private Nguoidung nguoidung;
	private Nhom nhom;

	public Nhomvanguoidung() {
	}

	public Nhomvanguoidung(NhomvanguoidungId id) {
		this.id = id;
	}

	public Nhomvanguoidung(NhomvanguoidungId id, Nguoidung nguoidung, Nhom nhom) {
		this.id = id;
		this.nguoidung = nguoidung;
		this.nhom = nhom;
	}

	public NhomvanguoidungId getId() {
		return this.id;
	}

	public void setId(NhomvanguoidungId id) {
		this.id = id;
	}

	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	public Nhom getNhom() {
		return this.nhom;
	}

	public void setNhom(Nhom nhom) {
		this.nhom = nhom;
	}

}
