package entity1;
// Generated Mar 24, 2023, 8:47:13 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhom generated by hbm2java
 */
@Entity
@Table(name = "nhom", catalog = "cuahangbangiay")
public class Nhom implements java.io.Serializable {

	private int idnhom;
	private String tenNhom;
	private Set<Nhomvanguoidung> nhomvanguoidungs = new HashSet<Nhomvanguoidung>(0);
	private Set<Phanquyen> phanquyens = new HashSet<Phanquyen>(0);

	public Nhom() {
	}

	public Nhom(int idnhom) {
		this.idnhom = idnhom;
	}

	public Nhom(int idnhom, String tenNhom, Set<Nhomvanguoidung> nhomvanguoidungs, Set<Phanquyen> phanquyens) {
		this.idnhom = idnhom;
		this.tenNhom = tenNhom;
		this.nhomvanguoidungs = nhomvanguoidungs;
		this.phanquyens = phanquyens;
	}

	@Id

	@Column(name = "IDNhom", unique = true, nullable = false)
	public int getIdnhom() {
		return this.idnhom;
	}

	public void setIdnhom(int idnhom) {
		this.idnhom = idnhom;
	}

	@Column(name = "TenNhom", length = 0)
	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhom")
	public Set<Nhomvanguoidung> getNhomvanguoidungs() {
		return this.nhomvanguoidungs;
	}

	public void setNhomvanguoidungs(Set<Nhomvanguoidung> nhomvanguoidungs) {
		this.nhomvanguoidungs = nhomvanguoidungs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhom")
	public Set<Phanquyen> getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set<Phanquyen> phanquyens) {
		this.phanquyens = phanquyens;
	}

}
