package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Nhom generated by hbm2java
 */
public class Nhom implements java.io.Serializable {

	private Integer idnhom;
	private String tenNhom;
	private Set phanquyens = new HashSet(0);

	public Nhom() {
	}

	public Nhom(String tenNhom, Set phanquyens) {
		this.tenNhom = tenNhom;
		this.phanquyens = phanquyens;
	}

	public Integer getIdnhom() {
		return this.idnhom;
	}

	public void setIdnhom(Integer idnhom) {
		this.idnhom = idnhom;
	}

	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	public Set getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set phanquyens) {
		this.phanquyens = phanquyens;
	}

}
