package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

/**
 * NhomvanguoidungId generated by hbm2java
 */
public class NhomvanguoidungId implements java.io.Serializable {

	private Integer idnguoiDung;
	private Integer idnhom;
	private String ghiChu;

	public NhomvanguoidungId() {
	}

	public NhomvanguoidungId(Integer idnguoiDung, Integer idnhom, String ghiChu) {
		this.idnguoiDung = idnguoiDung;
		this.idnhom = idnhom;
		this.ghiChu = ghiChu;
	}

	public Integer getIdnguoiDung() {
		return this.idnguoiDung;
	}

	public void setIdnguoiDung(Integer idnguoiDung) {
		this.idnguoiDung = idnguoiDung;
	}

	public Integer getIdnhom() {
		return this.idnhom;
	}

	public void setIdnhom(Integer idnhom) {
		this.idnhom = idnhom;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NhomvanguoidungId))
			return false;
		NhomvanguoidungId castOther = (NhomvanguoidungId) other;

		return ((this.getIdnguoiDung() == castOther.getIdnguoiDung()) || (this.getIdnguoiDung() != null
				&& castOther.getIdnguoiDung() != null && this.getIdnguoiDung().equals(castOther.getIdnguoiDung())))
				&& ((this.getIdnhom() == castOther.getIdnhom()) || (this.getIdnhom() != null
						&& castOther.getIdnhom() != null && this.getIdnhom().equals(castOther.getIdnhom())))
				&& ((this.getGhiChu() == castOther.getGhiChu()) || (this.getGhiChu() != null
						&& castOther.getGhiChu() != null && this.getGhiChu().equals(castOther.getGhiChu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdnguoiDung() == null ? 0 : this.getIdnguoiDung().hashCode());
		result = 37 * result + (getIdnhom() == null ? 0 : this.getIdnhom().hashCode());
		result = 37 * result + (getGhiChu() == null ? 0 : this.getGhiChu().hashCode());
		return result;
	}

}
