package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Nhom generated by hbm2java
 */
public class Nhom implements java.io.Serializable {

	private Integer idnhom;
	private String tenNhom;
	private Set<Phanquyen> phanquyens = new HashSet<Phanquyen>(0);
	private Set<Nhomvanguoidung> nhomvanguoidungs = new HashSet<Nhomvanguoidung>(0);

	public Nhom() {
	}

	public Nhom(String tenNhom, Set<Phanquyen> phanquyens, Set<Nhomvanguoidung> nhomvanguoidungs) {
		this.tenNhom = tenNhom;
		this.phanquyens = phanquyens;
		this.nhomvanguoidungs = nhomvanguoidungs;
	}

	public Integer getIdnhom() {
		return this.idnhom;
	}

	public void setIdnhom(Integer idnhom) {
		this.idnhom = idnhom;
	}

	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	public Set<Phanquyen> getPhanquyens() {
		return this.phanquyens;
	}

	public void setPhanquyens(Set<Phanquyen> phanquyens) {
		this.phanquyens = phanquyens;
	}

	public Set<Nhomvanguoidung> getNhomvanguoidungs() {
		return this.nhomvanguoidungs;
	}

	public void setNhomvanguoidungs(Set<Nhomvanguoidung> nhomvanguoidungs) {
		this.nhomvanguoidungs = nhomvanguoidungs;
	}

}
