package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phanloai generated by hbm2java
 */
@Entity
@Table(name = "phanloai", catalog = "cuahangbangiay")
public class Phanloai implements java.io.Serializable {

	private int idphanLoai;
	private String loai;
	private String mota;
	private Set<Giay> giays = new HashSet<Giay>(0);

	public Phanloai() {
	}

	public Phanloai(int idphanLoai) {
		this.idphanLoai = idphanLoai;
	}

	public Phanloai(int idphanLoai, String loai, String mota, Set<Giay> giays) {
		this.idphanLoai = idphanLoai;
		this.loai = loai;
		this.mota = mota;
		this.giays = giays;
	}

	@Id

	@Column(name = "IDPhanLoai", unique = true, nullable = false)
	public int getIdphanLoai() {
		return this.idphanLoai;
	}

	public void setIdphanLoai(int idphanLoai) {
		this.idphanLoai = idphanLoai;
	}

	@Column(name = "Loai", length = 0)
	public String getLoai() {
		return this.loai;
	}

	public void setLoai(String loai) {
		this.loai = loai;
	}

	@Column(name = "Mota", length = 0)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phanloai")
	public Set<Giay> getGiays() {
		return this.giays;
	}

	public void setGiays(Set<Giay> giays) {
		this.giays = giays;
	}

}
