package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

/**
 * Phanquyen generated by hbm2java
 */
public class Phanquyen implements java.io.Serializable {

	private PhanquyenId id;
	private Manhinh manhinh;
	private Nhom nhom;

	public Phanquyen() {
	}

	public Phanquyen(PhanquyenId id) {
		this.id = id;
	}

	public Phanquyen(PhanquyenId id, Manhinh manhinh, Nhom nhom) {
		this.id = id;
		this.manhinh = manhinh;
		this.nhom = nhom;
	}

	public PhanquyenId getId() {
		return this.id;
	}

	public void setId(PhanquyenId id) {
		this.id = id;
	}

	public Manhinh getManhinh() {
		return this.manhinh;
	}

	public void setManhinh(Manhinh manhinh) {
		this.manhinh = manhinh;
	}

	public Nhom getNhom() {
		return this.nhom;
	}

	public void setNhom(Nhom nhom) {
		this.nhom = nhom;
	}

}
