package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

/**
 * PhanquyenId generated by hbm2java
 */
public class PhanquyenId implements java.io.Serializable {

	private Integer idmanHinh;
	private Integer idnhom;
	private Boolean coQuyen;

	public PhanquyenId() {
	}

	public PhanquyenId(Integer idmanHinh, Integer idnhom, Boolean coQuyen) {
		this.idmanHinh = idmanHinh;
		this.idnhom = idnhom;
		this.coQuyen = coQuyen;
	}

	public Integer getIdmanHinh() {
		return this.idmanHinh;
	}

	public void setIdmanHinh(Integer idmanHinh) {
		this.idmanHinh = idmanHinh;
	}

	public Integer getIdnhom() {
		return this.idnhom;
	}

	public void setIdnhom(Integer idnhom) {
		this.idnhom = idnhom;
	}

	public Boolean getCoQuyen() {
		return this.coQuyen;
	}

	public void setCoQuyen(Boolean coQuyen) {
		this.coQuyen = coQuyen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhanquyenId))
			return false;
		PhanquyenId castOther = (PhanquyenId) other;

		return ((this.getIdmanHinh() == castOther.getIdmanHinh()) || (this.getIdmanHinh() != null
				&& castOther.getIdmanHinh() != null && this.getIdmanHinh().equals(castOther.getIdmanHinh())))
				&& ((this.getIdnhom() == castOther.getIdnhom()) || (this.getIdnhom() != null
						&& castOther.getIdnhom() != null && this.getIdnhom().equals(castOther.getIdnhom())))
				&& ((this.getCoQuyen() == castOther.getCoQuyen()) || (this.getCoQuyen() != null
						&& castOther.getCoQuyen() != null && this.getCoQuyen().equals(castOther.getCoQuyen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdmanHinh() == null ? 0 : this.getIdmanHinh().hashCode());
		result = 37 * result + (getIdnhom() == null ? 0 : this.getIdnhom().hashCode());
		result = 37 * result + (getCoQuyen() == null ? 0 : this.getCoQuyen().hashCode());
		return result;
	}

}
