package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

/**
 * Phanquyen generated by hbm2java
 */
public class Phanquyen implements java.io.Serializable {

	private PhanquyenId id;
	private Nhom nhom;

	public Phanquyen() {
	}

	public Phanquyen(PhanquyenId id) {
		this.id = id;
	}

	public Phanquyen(PhanquyenId id, Nhom nhom) {
		this.id = id;
		this.nhom = nhom;
	}

	public PhanquyenId getId() {
		return this.id;
	}

	public void setId(PhanquyenId id) {
		this.id = id;
	}

	public Nhom getNhom() {
		return this.nhom;
	}

	public void setNhom(Nhom nhom) {
		this.nhom = nhom;
	}

}
