package entity1;
// Generated Mar 30, 2023, 4:12:58 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieunhap generated by hbm2java
 */
public class Phieunhap implements java.io.Serializable {

	private Integer idphieuNhap;
	private Date ngayTaoPhieu;
	private Integer idnhanVien;
	private BigDecimal tongTienNhap;
	private Integer idnhaCungCap;
	private Set chitietphieunhaps = new HashSet(0);

	public Phieunhap() {
	}

	public Phieunhap(Date ngayTaoPhieu, Integer idnhanVien, BigDecimal tongTienNhap, Integer idnhaCungCap,
			Set chitietphieunhaps) {
		this.ngayTaoPhieu = ngayTaoPhieu;
		this.idnhanVien = idnhanVien;
		this.tongTienNhap = tongTienNhap;
		this.idnhaCungCap = idnhaCungCap;
		this.chitietphieunhaps = chitietphieunhaps;
	}

	public Integer getIdphieuNhap() {
		return this.idphieuNhap;
	}

	public void setIdphieuNhap(Integer idphieuNhap) {
		this.idphieuNhap = idphieuNhap;
	}

	public Date getNgayTaoPhieu() {
		return this.ngayTaoPhieu;
	}

	public void setNgayTaoPhieu(Date ngayTaoPhieu) {
		this.ngayTaoPhieu = ngayTaoPhieu;
	}

	public Integer getIdnhanVien() {
		return this.idnhanVien;
	}

	public void setIdnhanVien(Integer idnhanVien) {
		this.idnhanVien = idnhanVien;
	}

	public BigDecimal getTongTienNhap() {
		return this.tongTienNhap;
	}

	public void setTongTienNhap(BigDecimal tongTienNhap) {
		this.tongTienNhap = tongTienNhap;
	}

	public Integer getIdnhaCungCap() {
		return this.idnhaCungCap;
	}

	public void setIdnhaCungCap(Integer idnhaCungCap) {
		this.idnhaCungCap = idnhaCungCap;
	}

	public Set getChitietphieunhaps() {
		return this.chitietphieunhaps;
	}

	public void setChitietphieunhaps(Set chitietphieunhaps) {
		this.chitietphieunhaps = chitietphieunhaps;
	}

}
