package entity1;
// Generated May 9, 2023, 1:47:18 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sanpham generated by hbm2java
 */
public class Sanpham implements java.io.Serializable {

	private Integer idgiay;
	private Phanloai phanloai;
	private String ten;
	private Double size;
	private String mau;
	private String vatLieu;
	private byte[] anh;
	private BigDecimal giaBan;
	private Double soluong;
	private String themMoTa;
	private Set<Chitietphieunhap> chitietphieunhaps = new HashSet<Chitietphieunhap>(0);
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

	public Sanpham() {
	}

	public Sanpham(Phanloai phanloai, String ten, Double size, String mau, String vatLieu, byte[] anh,
			BigDecimal giaBan, Double soluong, String themMoTa, Set<Chitietphieunhap> chitietphieunhaps,
			Set<Chitiethoadon> chitiethoadons) {
		this.phanloai = phanloai;
		this.ten = ten;
		this.size = size;
		this.mau = mau;
		this.vatLieu = vatLieu;
		this.anh = anh;
		this.giaBan = giaBan;
		this.soluong = soluong;
		this.themMoTa = themMoTa;
		this.chitietphieunhaps = chitietphieunhaps;
		this.chitiethoadons = chitiethoadons;
	}

   
    public String toString(){
        return this.idgiay+""+this.giaBan+""+this.mau+""+this.size+""+this.ten+this.vatLieu+"";
    }


  
        
	public Integer getIdgiay() {
		return this.idgiay;
	}

	public void setIdgiay(Integer idgiay) {
		this.idgiay = idgiay;
	}

	public Phanloai getPhanloai() {
		return this.phanloai;
	}

	public void setPhanloai(Phanloai phanloai) {
		this.phanloai = phanloai;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Double getSize() {
		return this.size;
	}

	public void setSize(Double size) {
		this.size = size;
	}

	public String getMau() {
		return this.mau;
	}

	public void setMau(String mau) {
		this.mau = mau;
	}

	public String getVatLieu() {
		return this.vatLieu;
	}

	public void setVatLieu(String vatLieu) {
		this.vatLieu = vatLieu;
	}

	public byte[] getAnh() {
		return this.anh;
	}

	public void setAnh(byte[] anh) {
		this.anh = anh;
	}

	public BigDecimal getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(BigDecimal giaBan) {
		this.giaBan = giaBan;
	}

	public Double getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Double soluong) {
		this.soluong = soluong;
	}

	public String getThemMoTa() {
		return this.themMoTa;
	}

	public void setThemMoTa(String themMoTa) {
		this.themMoTa = themMoTa;
	}

	public Set<Chitietphieunhap> getChitietphieunhaps() {
		return this.chitietphieunhaps;
	}

	public void setChitietphieunhaps(Set<Chitietphieunhap> chitietphieunhaps) {
		this.chitietphieunhaps = chitietphieunhaps;
	}

	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

}
