package entity1;
// Generated Apr 12, 2023, 10:43:38 AM by Hibernate Tools 5.6.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * The generated by hbm2java
 */
public class The implements java.io.Serializable {

	private Integer idthe;
	private String loai;
	private Double heSo;
	private Set khachhangs = new HashSet(0);

	public The() {
	}

	public The(String loai, Double heSo, Set khachhangs) {
		this.loai = loai;
		this.heSo = heSo;
		this.khachhangs = khachhangs;
	}

	public Integer getIdthe() {
		return this.idthe;
	}

	public void setIdthe(Integer idthe) {
		this.idthe = idthe;
	}

	public String getLoai() {
		return this.loai;
	}

	public void setLoai(String loai) {
		this.loai = loai;
	}

	public Double getHeSo() {
		return this.heSo;
	}

	public void setHeSo(Double heSo) {
		this.heSo = heSo;
	}

	public Set getKhachhangs() {
		return this.khachhangs;
	}

	public void setKhachhangs(Set khachhangs) {
		this.khachhangs = khachhangs;
	}

}
