package entity1;
// Generated Mar 23, 2023, 7:01:00 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * The generated by hbm2java
 */
@Entity
@Table(name = "the", catalog = "cuahangbangiay")
public class The implements java.io.Serializable {

	private int idthe;
	private String loai;
	private Double heSo;
	private Set<Khachhang> khachhangs = new HashSet<Khachhang>(0);

	public The() {
	}

	public The(int idthe) {
		this.idthe = idthe;
	}

	public The(int idthe, String loai, Double heSo, Set<Khachhang> khachhangs) {
		this.idthe = idthe;
		this.loai = loai;
		this.heSo = heSo;
		this.khachhangs = khachhangs;
	}

	@Id

	@Column(name = "IDThe", unique = true, nullable = false)
	public int getIdthe() {
		return this.idthe;
	}

	public void setIdthe(int idthe) {
		this.idthe = idthe;
	}

	@Column(name = "Loai", length = 20)
	public String getLoai() {
		return this.loai;
	}

	public void setLoai(String loai) {
		this.loai = loai;
	}

	@Column(name = "HeSo", precision = 22, scale = 0)
	public Double getHeSo() {
		return this.heSo;
	}

	public void setHeSo(Double heSo) {
		this.heSo = heSo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "the")
	public Set<Khachhang> getKhachhangs() {
		return this.khachhangs;
	}

	public void setKhachhangs(Set<Khachhang> khachhangs) {
		this.khachhangs = khachhangs;
	}

}
